#!/bin/bash
printf '%s\n' "+++  $(pwd)/${BASH_SOURCE[0]} $(date)"

SECONDS=0
# cut and paste from spack info openmpi
myList="          3.0.0     http://www.open-mpi.org/software/ompi/v3.0/downloads/openmpi-3.0.0.tar.bz2"
myList="${myList} 2.1.3     http://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.3.tar.bz2"
myList="${myList} 2.1.2     http://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.2.tar.bz2"
myList="${myList} 2.1.1     http://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.1.tar.bz2"
myList="${myList} 2.1.0     http://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.0.tar.bz2"
myList="${myList} 2.0.4     http://www.open-mpi.org/software/ompi/v2.0/downloads/openmpi-2.0.4.tar.bz2"
myList="${myList} 2.0.3     http://www.open-mpi.org/software/ompi/v2.0/downloads/openmpi-2.0.3.tar.bz2"
myList="${myList} 2.0.2     http://www.open-mpi.org/software/ompi/v2.0/downloads/openmpi-2.0.2.tar.bz2"
myList="${myList} 2.0.1     http://www.open-mpi.org/software/ompi/v2.0/downloads/openmpi-2.0.1.tar.bz2"
myList="${myList} 2.0.0     http://www.open-mpi.org/software/ompi/v2.0/downloads/openmpi-2.0.0.tar.bz2"
myList="${myList} 1.10.7    http://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-1.10.7.tar.bz2"
myList="${myList} 1.10.6    http://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-1.10.6.tar.bz2"
myList="${myList} 1.10.5    http://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-1.10.5.tar.bz2"
myList="${myList} 1.10.4    http://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-1.10.4.tar.bz2"
myList="${myList} 1.10.3    http://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-1.10.3.tar.bz2"
myList="${myList} 1.10.2    http://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-1.10.2.tar.bz2"
myList="${myList} 1.10.1    http://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-1.10.1.tar.bz2"
myList="${myList} 1.10.0    http://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-1.10.0.tar.bz2"
myList="${myList} 1.8.8     http://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-1.8.8.tar.bz2"
myList="${myList} 1.8.7     http://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-1.8.7.tar.bz2"
myList="${myList} 1.8.6     http://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-1.8.6.tar.bz2"
myList="${myList} 1.8.5     http://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-1.8.5.tar.bz2"
myList="${myList} 1.8.4     http://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-1.8.4.tar.bz2"
myList="${myList} 1.8.3     http://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-1.8.3.tar.bz2"
myList="${myList} 1.8.2     http://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-1.8.2.tar.bz2"
myList="${myList} 1.8.1     http://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-1.8.1.tar.bz2"
myList="${myList} 1.8       http://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-1.8.tar.bz2"
myList="${myList} 1.7.5     http://www.open-mpi.org/software/ompi/v1.7/downloads/openmpi-1.7.5.tar.bz2"
myList="${myList} 1.7.4     http://www.open-mpi.org/software/ompi/v1.7/downloads/openmpi-1.7.4.tar.bz2"
myList="${myList} 1.7.3     http://www.open-mpi.org/software/ompi/v1.7/downloads/openmpi-1.7.3.tar.bz2"
myList="${myList} 1.7.2     http://www.open-mpi.org/software/ompi/v1.7/downloads/openmpi-1.7.2.tar.bz2"
myList="${myList} 1.7.1     http://www.open-mpi.org/software/ompi/v1.7/downloads/openmpi-1.7.1.tar.bz2"
myList="${myList} 1.7       http://www.open-mpi.org/software/ompi/v1.7/downloads/openmpi-1.7.tar.bz2"
myList="${myList} 1.6.5     http://www.open-mpi.org/software/ompi/v1.6/downloads/openmpi-1.6.5.tar.bz2"
myList="${myList} 1.6.4     http://www.open-mpi.org/software/ompi/v1.6/downloads/openmpi-1.6.4.tar.bz2"
myList="${myList} 1.6.3     http://www.open-mpi.org/software/ompi/v1.6/downloads/openmpi-1.6.3.tar.bz2"
myList="${myList} 1.6.2     http://www.open-mpi.org/software/ompi/v1.6/downloads/openmpi-1.6.2.tar.bz2"
myList="${myList} 1.6.1     http://www.open-mpi.org/software/ompi/v1.6/downloads/openmpi-1.6.1.tar.bz2"
myList="${myList} 1.6       http://www.open-mpi.org/software/ompi/v1.6/downloads/openmpi-1.6.tar.bz2"
myList="${myList} 1.5.5     http://www.open-mpi.org/software/ompi/v1.5/downloads/openmpi-1.5.5.tar.bz2"
myList="${myList} 1.5.4     http://www.open-mpi.org/software/ompi/v1.5/downloads/openmpi-1.5.4.tar.bz2"
myList="${myList} 1.5.3     http://www.open-mpi.org/software/ompi/v1.5/downloads/openmpi-1.5.3.tar.bz2"
myList="${myList} 1.5.2     http://www.open-mpi.org/software/ompi/v1.5/downloads/openmpi-1.5.2.tar.bz2"
myList="${myList} 1.5.1     http://www.open-mpi.org/software/ompi/v1.5/downloads/openmpi-1.5.1.tar.bz2"
myList="${myList} 1.5       http://www.open-mpi.org/software/ompi/v1.5/downloads/openmpi-1.5.tar.bz2"
myList="${myList} 1.4.5     http://www.open-mpi.org/software/ompi/v1.4/downloads/openmpi-1.4.5.tar.bz2"
myList="${myList} 1.4.4     http://www.open-mpi.org/software/ompi/v1.4/downloads/openmpi-1.4.4.tar.bz2"
myList="${myList} 1.4.3     http://www.open-mpi.org/software/ompi/v1.4/downloads/openmpi-1.4.3.tar.bz2"
myList="${myList} 1.4.2     http://www.open-mpi.org/software/ompi/v1.4/downloads/openmpi-1.4.2.tar.bz2"
myList="${myList} 1.4.1     http://www.open-mpi.org/software/ompi/v1.4/downloads/openmpi-1.4.1.tar.bz2"
myList="${myList} 1.4       http://www.open-mpi.org/software/ompi/v1.4/downloads/openmpi-1.4.tar.bz2"
myList="${myList} 1.3.4     http://www.open-mpi.org/software/ompi/v1.3/downloads/openmpi-1.3.4.tar.bz2"
myList="${myList} 1.3.3     http://www.open-mpi.org/software/ompi/v1.3/downloads/openmpi-1.3.3.tar.bz2"
myList="${myList} 1.3.2     http://www.open-mpi.org/software/ompi/v1.3/downloads/openmpi-1.3.2.tar.bz2"
myList="${myList} 1.3.1     http://www.open-mpi.org/software/ompi/v1.3/downloads/openmpi-1.3.1.tar.bz2"
myList="${myList} 1.3       http://www.open-mpi.org/software/ompi/v1.3/downloads/openmpi-1.3.tar.bz2"
myList="${myList} 1.2.9     http://www.open-mpi.org/software/ompi/v1.2/downloads/openmpi-1.2.9.tar.bz2"
myList="${myList} 1.2.8     http://www.open-mpi.org/software/ompi/v1.2/downloads/openmpi-1.2.8.tar.bz2"
myList="${myList} 1.2.7     http://www.open-mpi.org/software/ompi/v1.2/downloads/openmpi-1.2.7.tar.bz2"
myList="${myList} 1.2.6     http://www.open-mpi.org/software/ompi/v1.2/downloads/openmpi-1.2.6.tar.bz2"
myList="${myList} 1.2.5     http://www.open-mpi.org/software/ompi/v1.2/downloads/openmpi-1.2.5.tar.bz2"
myList="${myList} 1.2.4     http://www.open-mpi.org/software/ompi/v1.2/downloads/openmpi-1.2.4.tar.bz2"
myList="${myList} 1.2.3     http://www.open-mpi.org/software/ompi/v1.2/downloads/openmpi-1.2.3.tar.bz2"
myList="${myList} 1.2.2     http://www.open-mpi.org/software/ompi/v1.2/downloads/openmpi-1.2.2.tar.bz2"
myList="${myList} 1.2.1     http://www.open-mpi.org/software/ompi/v1.2/downloads/openmpi-1.2.1.tar.bz2"
myList="${myList} 1.2       http://www.open-mpi.org/software/ompi/v1.2/downloads/openmpi-1.2.tar.bz2"
myList="${myList} 1.1.5     http://www.open-mpi.org/software/ompi/v1.1/downloads/openmpi-1.1.5.tar.bz2"
myList="${myList} 1.1.4     http://www.open-mpi.org/software/ompi/v1.1/downloads/openmpi-1.1.4.tar.bz2"
myList="${myList} 1.1.3     http://www.open-mpi.org/software/ompi/v1.1/downloads/openmpi-1.1.3.tar.bz2"
myList="${myList} 1.1.2     http://www.open-mpi.org/software/ompi/v1.1/downloads/openmpi-1.1.2.tar.bz2"
myList="${myList} 1.1.1     http://www.open-mpi.org/software/ompi/v1.1/downloads/openmpi-1.1.1.tar.bz2"
myList="${myList} 1.1       http://www.open-mpi.org/software/ompi/v1.1/downloads/openmpi-1.1.tar.bz2"
myList="${myList} 1.0.2     http://www.open-mpi.org/software/ompi/v1.0/downloads/openmpi-1.0.2.tar.bz2"
myList="${myList} 1.0.1     http://www.open-mpi.org/software/ompi/v1.0/downloads/openmpi-1.0.1.tar.bz2"
myList="${myList} 1.0       http://www.open-mpi.org/software/ompi/v1.0/downloads/openmpi-1.0.tar.bz2"

let "s = 1"
for m in ${myList}; do
    let "s = s * -1"
    if [ $s == 1 ]
    then
      echo "wget ${m}"
            wget ${m}
    fi
done

echo "time used = ${SECONDS} s"
